
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author harun
 */
public class anaMenu extends javax.swing.JFrame {

    /**
     * Creates new form anaMenu
     */
    User user;
    public anaMenu(User user) {
        initComponents();
        this.user = user;
        this.setTitle("Çarpım Tablosu");
        ImageIcon icon = new ImageIcon("carpp.png");
        this.setIconImage(icon.getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        question q1 = new question(10);
        alistirmaVar1.setText(String.valueOf(q1.getNumber1())); 
        alistirmaVar2.setText(String.valueOf(q1.getNumber2()));
        alistirmaVar1.setOpaque(true);
        alistirmaVar2.setOpaque(true);
        odevSayi1.setOpaque(true);
        odevSayi2.setOpaque(true);
        
        
        
        
        carpimTablosu.setIcon(boyutAyarla(new ImageIcon("table.jpg"), 649, 502));

    }

    private String toString(int number1) {
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        odevler = new javax.swing.JPanel();
        odevSayi1 = new javax.swing.JLabel();
        odevSayi2 = new javax.swing.JLabel();
        odevCevap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cevapOnay = new javax.swing.JButton();
        startOdev = new javax.swing.JButton();
        raporlar = new javax.swing.JPanel();
        carpimTablosu = new javax.swing.JLabel();
        alistirmalar = new javax.swing.JPanel();
        alistirmaVar1 = new javax.swing.JLabel();
        alistirmaVar2 = new javax.swing.JLabel();
        alistirmaAnswer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        alistirmaRangetaker = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(244, 244, 255));
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        odevler.setBackground(new java.awt.Color(255, 244, 244));

        odevSayi1.setBackground(new java.awt.Color(255, 255, 255));
        odevSayi1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odevSayi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        odevSayi1.setText("Sayi 1");

        odevSayi2.setBackground(new java.awt.Color(255, 255, 255));
        odevSayi2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odevSayi2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        odevSayi2.setText("sayi 2");

        odevCevap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odevCevap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        odevCevap.setText("Cevap");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");

        cevapOnay.setText("SONRAKİ SORU");

        startOdev.setText("START");
        startOdev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startOdevMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout odevlerLayout = new javax.swing.GroupLayout(odevler);
        odevler.setLayout(odevlerLayout);
        odevlerLayout.setHorizontalGroup(
            odevlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(odevlerLayout.createSequentialGroup()
                .addGroup(odevlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(odevlerLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(odevlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cevapOnay, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(odevlerLayout.createSequentialGroup()
                                .addComponent(odevSayi1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(odevSayi2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(odevCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(odevlerLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(startOdev, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        odevlerLayout.setVerticalGroup(
            odevlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(odevlerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(startOdev, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(odevlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(odevlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(odevCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(odevSayi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(odevSayi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(cevapOnay, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("                     ÖDEVLER                   ", odevler);

        raporlar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout raporlarLayout = new javax.swing.GroupLayout(raporlar);
        raporlar.setLayout(raporlarLayout);
        raporlarLayout.setHorizontalGroup(
            raporlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raporlarLayout.createSequentialGroup()
                .addComponent(carpimTablosu, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );
        raporlarLayout.setVerticalGroup(
            raporlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carpimTablosu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("              ÇARPIM TABLOSU              ", raporlar);

        alistirmaVar1.setBackground(new java.awt.Color(255, 255, 255));
        alistirmaVar1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        alistirmaVar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alistirmaVar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        alistirmaVar2.setBackground(new java.awt.Color(255, 255, 255));
        alistirmaVar2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        alistirmaVar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alistirmaVar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        alistirmaAnswer.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        alistirmaAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alistirmaAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        alistirmaAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alistirmaAnswerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("=");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("ONAYLA");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("ARALIK GİRİNİZ :");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("SORU ÜRET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");

        javax.swing.GroupLayout alistirmalarLayout = new javax.swing.GroupLayout(alistirmalar);
        alistirmalar.setLayout(alistirmalarLayout);
        alistirmalarLayout.setHorizontalGroup(
            alistirmalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alistirmalarLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(alistirmalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alistirmalarLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alistirmaRangetaker, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alistirmalarLayout.createSequentialGroup()
                        .addComponent(alistirmaVar1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alistirmalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alistirmalarLayout.createSequentialGroup()
                        .addComponent(alistirmaVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alistirmaAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(alistirmalarLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alistirmalarLayout.setVerticalGroup(
            alistirmalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alistirmalarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alistirmalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alistirmaRangetaker, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(alistirmalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alistirmalarLayout.createSequentialGroup()
                        .addGroup(alistirmalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alistirmaVar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alistirmaVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(alistirmalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(alistirmaAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alistirmalarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("             ALIŞTIRMALAR                      ", alistirmalar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!alistirmaRangetaker.getText().equals("")){
            question q1 = new question(Integer.parseInt(alistirmaRangetaker.getText()));
            alistirmaVar1.setText(String.valueOf(q1.getNumber1()));
            alistirmaVar2.setText(String.valueOf(q1.getNumber2()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Sayı girmediğinizden dolayı 0-10 arası değer aralığı atandı.");
            question q1 = new question(user.getQuestionRange());
            alistirmaVar1.setText(String.valueOf(q1.getNumber1()));
            alistirmaVar2.setText(String.valueOf(q1.getNumber2()));
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        //want to check if input is integer or not
        if(alistirmaAnswer.getText().matches("[0-9]+"))        {
            if(Integer.parseInt(alistirmaVar1.getText())*Integer.parseInt(alistirmaVar2.getText()) == Integer.parseInt(alistirmaAnswer.getText()))
            {
                JOptionPane.showMessageDialog(null, "Doğru cevap tebrikler! Bir sonraki soru");
            }
            else{
                JOptionPane.showMessageDialog(null, "Bilemediniz, Alıştırma yapmaya devam edin!");
            }
            alistirmaAnswer.setText("");
            if(!alistirmaRangetaker.getText().equals("")){
                question q1 = new question(Integer.parseInt(alistirmaRangetaker.getText()));
                alistirmaVar1.setText(String.valueOf(q1.getNumber1()));
                alistirmaVar2.setText(String.valueOf(q1.getNumber2()));
            }
            else{
                question q1 = new question(10);
                alistirmaVar1.setText(String.valueOf(q1.getNumber1()));
                alistirmaVar2.setText(String.valueOf(q1.getNumber2()));
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Lütfen sayısal bir değer giriniz!");
        }

        // if(Integer.parseInt(alistirmaVar1.getText())*Integer.parseInt(alistirmaVar2.getText()) == Integer.parseInt(alistirmaAnswer.getText()))
        // {
            //     JOptionPane.showMessageDialog(null, "Doğru cevap tebrikler! Bir sonraki soru");
            // }
        // else{
            //     JOptionPane.showMessageDialog(null, "Bilemediniz, Alıştırma yapmaya devam edin!");
            // }
        // alistirmaAnswer.setText("");
        // if(!alistirmaRangetaker.getText().equals("")){
            //     question q1 = new question(Integer.parseInt(alistirmaRangetaker.getText()));
            //     alistirmaVar1.setText(String.valueOf(q1.getNumber1()));
            //     alistirmaVar2.setText(String.valueOf(q1.getNumber2()));
            // }
        // else{
            //     question q1 = new question(10);
            //     alistirmaVar1.setText(String.valueOf(q1.getNumber1()));
            //     alistirmaVar2.setText(String.valueOf(q1.getNumber2()));
            // }
        // // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void alistirmaAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alistirmaAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alistirmaAnswerActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
  // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    @SuppressWarnings("empty-statement")
    private void startOdevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startOdevMouseClicked
     
        JOptionPane.showMessageDialog(null, "Odev Sorularınız Başladı!");
        int i;
        //take the status of the exam and write it to the excel file without any class
        //true and false question answers are written to the excel file
        //if the answer is true, it is written as 1, if it is false, it is written as 0
        //time will be taken too
        //declare the list of questions
        //and excel file
        //write code
        int answers[] = new int[user.getQuestionNumber()];
        //excel
        


//        for(i = 0 ; i < user.getQuestionNumber() ; i++){
//            question qq = new question(user.getQuestionRange());               
//            odevSayi1.setText(String.valueOf(qq.getNumber1()));
//            odevSayi2.setText(String.valueOf(qq.getNumber2()));
//            odevAnswer.setText("");
//            while(!odevAnswer.getText().matches("[0-9]+")){
//                JOptionPane.showMessageDialog(null, "Lütfen sayısal bir değer giriniz!");
//                odevAnswer.setText("");
//            }
//            if(Integer.parseInt(odevSayi1.getText())*Integer.parseInt(odevSayi2.getText()) == Integer.parseInt(odevAnswer.getText())){
//                JOptionPane.showMessageDialog(null, "Doğru cevap tebrikler! Bir sonraki soru");
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "Bilemediniz, Alıştırma yapmaya devam edin!");
//            }
//        }
//        JOptionPane.showMessageDialog(null, "Odev Sorularınız Bitti!");

        

        // TODO add your handling code here:
    }//GEN-LAST:event_startOdevMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(anaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(anaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(anaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(anaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new anaMenu(new User).setVisible(true);
//            }
//        });
//    }
    	static ImageIcon boyutAyarla(ImageIcon imageIcon, int width, int height) {
    	Image image = imageIcon.getImage();
    	Image newimg = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
    	imageIcon = new ImageIcon(newimg);
    	return imageIcon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alistirmaAnswer;
    private javax.swing.JTextField alistirmaRangetaker;
    private javax.swing.JLabel alistirmaVar1;
    private javax.swing.JLabel alistirmaVar2;
    private javax.swing.JPanel alistirmalar;
    private javax.swing.JLabel carpimTablosu;
    private javax.swing.JButton cevapOnay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField odevCevap;
    private javax.swing.JLabel odevSayi1;
    private javax.swing.JLabel odevSayi2;
    private javax.swing.JPanel odevler;
    private javax.swing.JPanel raporlar;
    private javax.swing.JButton startOdev;
    // End of variables declaration//GEN-END:variables
}
