import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author harun
 */
public class Registration extends javax.swing.JFrame {

    private final Login turnBack;
    private final ArrayList<User> users;
    /**
     * Creates new form NewJFrame
     * @param turnBack
     * @param users
     */
    public Registration(Login turnBack, ArrayList<User> users) {
        this.setTitle("Çarpım Tablosu");
        ImageIcon icon = new ImageIcon("carpp.png");
        this.setIconImage(icon.getImage());
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.turnBack = turnBack;
        this.users = users;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDtakerReg = new javax.swing.JTextField();
        PasswordTakerReg = new javax.swing.JTextField();
        PasswordAgain = new javax.swing.JTextField();
        regOnayButton = new javax.swing.JButton();
        geriButtonReg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ÇARPIM TABLOSU KAYIT");

        IDtakerReg.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        IDtakerReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDtakerReg.setText("Kullanıcı Adı");
        IDtakerReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IDtakerRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IDtakerRegMouseExited(evt);
            }
        });
        IDtakerReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtakerRegActionPerformed(evt);
            }
        });
        IDtakerReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDtakerRegKeyPressed(evt);
            }
        });

        PasswordTakerReg.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        PasswordTakerReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTakerReg.setText("Parola");
        PasswordTakerReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordTakerRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordTakerRegMouseExited(evt);
            }
        });
        PasswordTakerReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTakerRegActionPerformed(evt);
            }
        });
        PasswordTakerReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordTakerRegKeyPressed(evt);
            }
        });

        PasswordAgain.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        PasswordAgain.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordAgain.setText("Parola (Tekrar)");
        PasswordAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordAgainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordAgainMouseExited(evt);
            }
        });
        PasswordAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordAgainActionPerformed(evt);
            }
        });
        PasswordAgain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordAgainKeyPressed(evt);
            }
        });

        regOnayButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        regOnayButton.setText("KAYDOL");
        regOnayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regOnayButtonMouseClicked(evt);
            }
        });
        regOnayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regOnayButtonActionPerformed(evt);
            }
        });

        geriButtonReg.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        geriButtonReg.setText("<< GERİ");
        geriButtonReg.setAlignmentY(0.0F);
        geriButtonReg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        geriButtonReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriButtonRegMouseClicked(evt);
            }
        });
        geriButtonReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriButtonRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(geriButtonReg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(regOnayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IDtakerReg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PasswordTakerReg)
                        .addComponent(PasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(IDtakerReg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(PasswordTakerReg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(PasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regOnayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geriButtonReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtakerRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDtakerRegMouseEntered
        if(IDtakerReg.getText().equals("Kullanıcı Adı"))
        IDtakerReg.setText("");

    }//GEN-LAST:event_IDtakerRegMouseEntered

    private void IDtakerRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDtakerRegMouseExited
        if(IDtakerReg.getText().equals(""))
        IDtakerReg.setText("Kullanıcı Adı");
    }//GEN-LAST:event_IDtakerRegMouseExited

    private void IDtakerRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtakerRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtakerRegActionPerformed

    private void PasswordTakerRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTakerRegMouseEntered
        if(PasswordTakerReg.getText().equals("Parola"))
        PasswordTakerReg.setText("");

    }//GEN-LAST:event_PasswordTakerRegMouseEntered

    private void PasswordTakerRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTakerRegMouseExited
        if(PasswordTakerReg.getText().equals(""))
        PasswordTakerReg.setText("Parola");
    }//GEN-LAST:event_PasswordTakerRegMouseExited

    private void PasswordTakerRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTakerRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTakerRegActionPerformed

    private void PasswordAgainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordAgainMouseEntered
        if(PasswordAgain.getText().equals("Parola (Tekrar)"))
            PasswordAgain.setText("");

    }//GEN-LAST:event_PasswordAgainMouseEntered

    private void PasswordAgainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordAgainMouseExited
        if(PasswordAgain.getText().equals(""))
            PasswordAgain.setText("Parola (Tekrar)");
    }//GEN-LAST:event_PasswordAgainMouseExited

    private void PasswordAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordAgainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordAgainActionPerformed

    private void regOnayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regOnayButtonMouseClicked
        
        if(!IDtakerReg.getText().equals("Kullanıcı Adı") &&
           !PasswordTakerReg.getText().equals("Parola")&&
            PasswordTakerReg.getText().equals(PasswordAgain.getText()))
        {           
            this.setVisible(false);
            turnBack.setVisible(rootPaneCheckingEnabled);
            users.add(new User(IDtakerReg.getText(),PasswordTakerReg.getText()));
            JOptionPane.showMessageDialog(this,"Kayıt Başarılı.");
            turnBack.saveUserstoFile("users.dat");
            this.dispose();
            
            
        }
        
        else if(!IDtakerReg.getText().equals("Kullanıcı Adı") &&
                !PasswordTakerReg.getText().equals("Parola")&&
                !PasswordTakerReg.getText().equals(PasswordAgain.getText()))
        {
                JOptionPane.showMessageDialog(this,"Parolalarınız eşleşmiyor.");  
        }
        
        else{
                JOptionPane.showMessageDialog(this,"Bilgilerinizi eksiksiz giriniz."); 
        }
            
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_regOnayButtonMouseClicked

    private void regOnayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regOnayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regOnayButtonActionPerformed

    private void geriButtonRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriButtonRegMouseClicked
            this.setVisible(false);
            turnBack.setVisible(rootPaneCheckingEnabled);       
            this.dispose();        
        // TODO add your handling code here:
    }//GEN-LAST:event_geriButtonRegMouseClicked

    private void geriButtonRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriButtonRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geriButtonRegActionPerformed

    private void IDtakerRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDtakerRegKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            PasswordTakerReg.setText("");
            PasswordTakerReg.requestFocus();
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_IDtakerRegKeyPressed

    private void PasswordTakerRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTakerRegKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            PasswordAgain.setText("");
            PasswordAgain.requestFocus();
        }
    }//GEN-LAST:event_PasswordTakerRegKeyPressed

    private void PasswordAgainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordAgainKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            regOnayButtonMouseClicked(null);
        }
        // T
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordAgainKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registration().setVisible(true);
//            }
//        });
//    }
    static ImageIcon boyutAyarla(ImageIcon imageIcon, int width, int height) {
    	Image image = imageIcon.getImage();
    	Image newimg = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
    	imageIcon = new ImageIcon(newimg);
    	return imageIcon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDtakerReg;
    private javax.swing.JTextField PasswordAgain;
    private javax.swing.JTextField PasswordTakerReg;
    private javax.swing.JButton geriButtonReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regOnayButton;
    // End of variables declaration//GEN-END:variables
}
